-- vim.api.nvim_create_autocmd("FileType", {
-- 	pattern = "oil",
-- 	callback = function()
-- 		vim.opt_local.colorcolumn = ""
-- 	end,
-- })

return {
	-- "stevearc/oil.nvim",
	-- opts = {
	-- 	view_options = {
	-- 		show_hidden = true,
	-- 	},
	-- 	delete_to_trash = true,
	-- 	skip_confirm_for_simple_edits = true,
	-- 	keymaps = {
	-- 		["?"] = "actions.show_help",
	-- 		["<CR>"] = "actions.select",
	-- 		["<leader>o\\"] = "actions.select_vsplit",
	-- 		["<leader>o-"] = "actions.select_split", -- this is used to navigate left
	-- 		["<leader>or"] = "actions.refresh",
	-- 		["<leader>os"] = "actions.change_sort",
	-- 		["<leader>ox"] = "actions.open_external",
	-- 		["<leader>oh"] = "actions.toggle_hidden",
	-- 		["<leader>ot"] = "actions.toggle_trash",
	-- 		["-"] = "actions.parent",
	-- 		["_"] = "actions.open_cwd",
	-- 	},
	-- 	use_default_keymaps = false,
	-- 	experimental_watch_for_changes = true,
	-- },
	-- -- Optional dependencies
	-- dependencies = { "nvim-tree/nvim-web-devicons" },
	-- keys = {
	-- 	{
	-- 		"<leader>e",
	-- 		mode = { "n" },
	-- 		function()
	-- 			require("oil").toggle_float()
	-- 		end,
	-- 		desc = "[E]xplorer",
	-- 	},
	-- 	{
	-- 		"<leader>E",
	-- 		mode = { "n" },
	-- 		function()
	-- 			require("oil").toggle_float(vim.fn.getcwd())
	-- 		end,
	-- 		desc = "[E]xplorer (CWD)",
	-- 	},
	-- },
}
