#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_zoom_persist on
yabai -m config window_shadow on
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.15
yabai -m config window_animation_duration 0.15
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.85
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance off
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 8

# spaces
yabai -m space 1 --label "Browser"
yabai -m space 2 --label "Terminal"
yabai -m space 3 --label "Notes"
yabai -m space 4 --label "Social"
yabai -m space 5 --label "Productivity"
yabai -m space 6 --label "Work"
yabai -m space 7 --label "Music"

# Web browsers
yabai -m rule --add app="^(Google Chrome|Safari|Arc|Microsoft Edge|Safari Technology Preview|Firefox)$" space=1
# Terminal
yabai -m rule --add app="^(Terminal|Alacritty)$" space=2
# Notes
yabai -m rule --add app="^(Notes|Reminders|Obsidian)$" space=3
# Social
yabai -m rule --add app="^(WhatsApp|Messages|chatMate for WhatsApp)$" space=4
# Productivity
yabai -m rule --add app="^(Mail|Calendar)$" space=5
# Work
yabai -m rule --add app="^(Adobe Photoshop 2024|Adobe Illustrator 2024)$" space=6
# Music
yabai -m rule --add app="^(Music)$" space=7

# apps to not manage (ignore)
yabai -m rule --add app="^(Finder|System Settings|Archive Utility|Microsoft Excel|Creative Cloud|Logi Options|Raycast|Karabiner-Elements|Karabiner-EventViewer|Stats|FaceTime|Loom)$" manage=off

echo "yabai configuration loaded.."
