return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "beautysh",
        "biome",
        "bash-language-server",
        "css-lsp",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint-lsp",
        "eslint_d",
        "html-lsp",
        "json-lsp",
        "jsonlint",
        "lua-language-server",
        "markdownlint",
        "marksman",
        "prettierd",
        "prisma-language-server",
        "rnix-lsp",
        "stylua",
        "tailwindcss-language-server",
        "typescript-language-server",
        "yaml-language-server",
        "yamllint",
        "luacheck",
        "shellcheck",
        "yamlfmt",
        "shfmt",
      },
    },
  },
}
