return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "beautysh",
        "biome",
        "bash-language-server",
        "css-lsp",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint-lsp",
        "eslint_d",
        "html-lsp",
        "json-lsp",
        "jsonlint",
        "lua-language-server",
        "markdownlint",
        "marksman",
        "prettierd",
        "prisma-language-server",
        "nil",
        "stylua",
        "tailwindcss-language-server",
        "typescript-language-server",
        "yaml-language-server",
        "yamllint",
        "luacheck",
        "shellcheck",
        "yamlfmt",
        "shfmt",
      },
    },
  },
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        cssls = {},
        biome = {},
        html = {},
        lua_ls = {},
        prismals = {},
        nil_ls = {},
        bashls = {},
        docker_compose_language_service = {},
        dockerls = {},
      },
    },
  },
}
