return {
	"williamboman/mason.nvim",
	opts = {
		ensure_installed = {
			"beautysh",
			"biome",
			"prettierd",
			"json-lsp",
			"jsonlint",
			"lua-language-server",
			"markdownlint",
			"marksman",
			"prisma-language-server",
			"nil",
			"stylua",
			"tailwindcss-language-server",
			"typescript-language-server",
			"yaml-language-server",
			"yamllint",
			"luacheck",
			"shellcheck",
			"yamlfmt",
		},
	},
}
